name: Bug report
description: "Report a Bug"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Before submitting:
        - Is your OpenDTU up to date? [Releases](https://github.com/tbnobody/OpenDTU/releases)  
  - type: textarea
    id: what_happend
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expect_to_happen
    attributes:
      label: What did you expect to happen?
      placeholder: I expected that ...
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce it (minimal and precise)
      placeholder: First do this, than this..
    validations:
      required: false
  - type: input
    id: opendtu_version
    attributes:
      label: OpenDTU version
      placeholder: 0.0.0
    validations:
      required: true
  - type: input
    id: adapter_version
    attributes:
      label: Adapter version
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
    validations:
      required: false
